### ISSUE TITLE
bootkube cannot recover from full control plane loss

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-incubator/bootkube#333] opened 2017-02-26 18:10 UTC
## Background
When a self-hosted cluster experiences full control plane loss, i.e. all master nodes cannot be recovered, it's desirable to:
1. Launch a new controller node
2. Reboot bootkube's temporary control plane on that node
3. Have a new API server deployed to the k8s cluster and resume operation.

## Issue
When bootkube starts on a new control plane node, it reads from etcd and its StatusController reports that the self-hosted components are already deployed. The bootkube-provided temporary control plane then exits.

```
-- Logs begin at Sun 2017-02-26 18:52:39 UTC. --
Feb 26 18:54:46 ip-10-0-19-18 systemd[1]: Started Bootstrap a Kubernetes control plane with a temp api-server.
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: pubkey: prefix: "quay.io/coreos/bootkube"
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: key: "https://quay.io/aci-signing-key"
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: gpg key fingerprint is: BFF3 13CD AA56 0B16 A898  7B8F 72AB F5F6 799D 33BC
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]:         Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: Trusting "https://quay.io/aci-signing-key" for prefix "quay.io/coreos/bootkube" without fingerprint review.
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: Added key for prefix "quay.io/coreos/bootkube" at "/etc/rkt/trustedkeys/prefix.d/quay.io/coreos/bootkube/bff313cdaa560b16a8987b8f72abf5f6799d33bc"
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: Downloading signature:  0 B/473 B
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: Downloading signature:  473 B/473 B
Feb 26 18:54:46 ip-10-0-19-18 bootkube-start[2222]: Downloading signature:  473 B/473 B
Feb 26 18:54:47 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  0 B/29.6 MB
Feb 26 18:54:47 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  16.3 KB/29.6 MB
Feb 26 18:54:48 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  5.73 MB/29.6 MB
Feb 26 18:54:49 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  11 MB/29.6 MB
Feb 26 18:54:50 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  16.2 MB/29.6 MB
Feb 26 18:54:51 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  25.3 MB/29.6 MB
Feb 26 18:54:52 ip-10-0-19-18 bootkube-start[2222]: Downloading ACI:  29.6 MB/29.6 MB
Feb 26 18:54:52 ip-10-0-19-18 bootkube-start[2222]: image: signature verified:
Feb 26 18:54:52 ip-10-0-19-18 bootkube-start[2222]:   Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.925815] bootkube[5]: Running temporary bootstrap control plane...
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.926412] bootkube[5]: E0226 18:55:01.163799       5 server.go:78] unable to register configz: register config "componentconfig" twice
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.927320] bootkube[5]: E0226 18:55:01.164747       5 leaderelection.go:228] error retrieving resource lock kube-system/kube-scheduler: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/endpoints/kube-scheduler: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.927575] bootkube[5]: E0226 18:55:01.164747       5 leaderelection.go:228] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.927854] bootkube[5]: Waiting for api-server...
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.928388] bootkube[5]: I0226 18:55:01.165811       5 config.go:498] Will report 10.0.19.18 as public IP address.
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.931134] bootkube[5]: E0226 18:55:01.168559       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/pkg/bootkube/status.go:86: Failed to list *v1.Pod: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.931676] bootkube[5]: E0226 18:55:01.168619       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:481: Failed to list *extensions.ReplicaSet: Get http://127.0.0.1:8080/apis/extensions/v1beta1/replicasets?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.932181] bootkube[5]: E0226 18:55:01.168657       5 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.PersistentVolumeClaim: Get http://127.0.0.1:8080/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.932660] bootkube[5]: E0226 18:55:01.168698       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:473: Failed to list *api.ReplicationController: Get http://127.0.0.1:8080/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.933185] bootkube[5]: E0226 18:55:01.168732       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:470: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.933661] bootkube[5]: E0226 18:55:01.168764       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:466: Failed to list *api.PersistentVolume: Get http://127.0.0.1:8080/api/v1/persistentvolumes?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.934164] bootkube[5]: E0226 18:55:01.168796       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:463: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.934653] bootkube[5]: E0226 18:55:01.168844       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:460: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%21%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.935154] bootkube[5]: E0226 18:55:01.168880       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:457: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.935632] bootkube[5]: E0226 18:55:01.169837       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://127.0.0.1:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  141.936139] bootkube[5]: E0226 18:55:01.169878       5 reflector.go:199] github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1/serviceaccounts?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.018658] bootkube[5]: E0226 18:55:01.256079       5 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1/namespaces?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.030305] bootkube[5]: [restful] 2017/02/26 18:55:01 log.go:30: [restful/swagger] listing is available at https://10.0.19.18:443/swaggerapi/
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.030846] bootkube[5]: [restful] 2017/02/26 18:55:01 log.go:30: [restful/swagger] https://10.0.19.18:443/swaggerui/ is mapped to folder /swagger-ui/
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.078901] bootkube[5]: I0226 18:55:01.316306       5 serve.go:93] Serving securely on 0.0.0.0:443
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.079323] bootkube[5]: I0226 18:55:01.316426       5 serve.go:107] Serving insecurely on 127.0.0.1:8080
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.106556] bootkube[5]: W0226 18:55:01.343960       5 controller.go:392] Resetting endpoints for master service "kubernetes" to &TypeMeta{Kind:,APIVersion:,}
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.143070] bootkube[5]: I0226 18:55:01.380479       5 log.go:19] http: TLS handshake error from 10.0.9.194:46285: EOF
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.143685] bootkube[5]: I0226 18:55:01.381125       5 log.go:19] http: TLS handshake error from 10.0.9.194:46287: EOF
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.147567] bootkube[5]: I0226 18:55:01.385001       5 log.go:19] http: TLS handshake error from 10.0.9.194:46289: EOF
Feb 26 18:55:01 ip-10-0-19-18 bootkube-start[2222]: [  142.148550] bootkube[5]: I0226 18:55:01.385991       5 log.go:19] http: TLS handshake error from 10.0.9.194:46313: EOF
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.027821] bootkube[5]: I0226 18:55:02.265235       5 trace.go:61] Trace "Create /api/v1/namespaces/default/events" (started 2017-02-26 18:55:01.460345638 +0000 UTC):
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.028237] bootkube[5]: [55.79µs] [55.79µs] About to convert to expected version
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.028779] bootkube[5]: [125.32µs] [69.53µs] Conversion done
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.029009] bootkube[5]: [801.892451ms] [801.767131ms] About to store object in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.029570] bootkube[5]: [804.80633ms] [2.913879ms] Object stored in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.029965] bootkube[5]: [804.828972ms] [22.642µs] Self-link added
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.030421] bootkube[5]: [804.862649ms] [33.677µs] END
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.038381] bootkube[5]: I0226 18:55:02.275802       5 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/events" (started 2017-02-26 18:55:01.470736422 +0000 UTC):
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.038727] bootkube[5]: [32.135µs] [32.135µs] About to convert to expected version
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.039042] bootkube[5]: [89.235µs] [57.1µs] Conversion done
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.039273] bootkube[5]: [802.728711ms] [802.639476ms] About to store object in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.039507] bootkube[5]: [805.007352ms] [2.278641ms] Object stored in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.039729] bootkube[5]: [805.011614ms] [4.262µs] Self-link added
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.039910] bootkube[5]: [805.037798ms] [26.184µs] END
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.111676] bootkube[5]: I0226 18:55:02.349090       5 trace.go:61] Trace "GuaranteedUpdate etcd3: *api.Endpoints" (started 2017-02-26 18:55:01.344871675 +0000 UTC):
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.112546] bootkube[5]: [37.589µs] [37.589µs] initial value restored
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.112738] bootkube[5]: [1.002992467s] [1.002954878s] Transaction prepared
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.112915] bootkube[5]: [1.004149931s] [1.157464ms] Transaction committed
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.113106] bootkube[5]: [1.004196598s] [46.667µs] END
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.113498] bootkube[5]: I0226 18:55:02.349168       5 trace.go:61] Trace "Update /api/v1/namespaces/default/endpoints/kubernetes" (started 2017-02-26 18:55:01.344776001 +0000 UTC):
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.113688] bootkube[5]: [12.003µs] [12.003µs] About to convert to expected version
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.113867] bootkube[5]: [55.746µs] [43.743µs] Conversion done
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.114039] bootkube[5]: [59.883µs] [4.137µs] About to store object in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.114237] bootkube[5]: [1.004336913s] [1.00427703s] Object stored in database
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.114408] bootkube[5]: [1.004340117s] [3.204µs] Self-link added
Feb 26 18:55:02 ip-10-0-19-18 bootkube-start[2222]: [  143.114578] bootkube[5]: [1.004375587s] [35.47µs] END
Feb 26 18:55:04 ip-10-0-19-18 bootkube-start[2222]: [  145.380459] bootkube[5]: I0226 18:55:04.617862       5 leaderelection.go:247] lock is held by kube-controller-manager-3004739813-0nd5x and has not yet expired
Feb 26 18:55:05 ip-10-0-19-18 bootkube-start[2222]: [  146.186535] bootkube[5]: I0226 18:55:05.423951       5 leaderelection.go:247] lock is held by kube-scheduler-2947727816-czclv and has not yet expired
Feb 26 18:55:06 ip-10-0-19-18 bootkube-start[2222]: [  146.926584] bootkube[5]: All self-hosted control plane components successfully started
Feb 26 18:55:06 ip-10-0-19-18 bootkube-start[2222]: Waiting for Kubernetes API...
Feb 26 18:55:11 ip-10-0-19-18 bootkube-start[2222]: Waiting for Kubernetes API...
```

The only way I've been able to get the api-server to redeploy, is to remove it from the registry (in etcd) manually.

```
etcdctl get --prefix=true --keys-only /registry | grep kube-apiserver- | xargs -L1 etcdctl del
```

I've also found the same must be done for the `kube-scheduler` and `kube-controller-manager`.

On a related note, I've found that when Tectonic's thirdparty resources are present in the etcd registry, bootkube panics and exits due to `invalid memory address or nil pointer dereference`. Details can be found in #334.

## Versions
k8s [hyperkube] version: [1.5.2_coreos.2](https://github.com/coreos/kubernetes/tree/v1.5.2+coreos.2)
version: [v0.3.7](https://github.com/kubernetes-incubator/bootkube/tree/v0.3.7)
os: 
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.12.0
VERSION_ID=1235.12.0
BUILD_ID=2017-02-23-0222
PRETTY_NAME="Container Linux by CoreOS 1235.12.0 (Ladybug)"
```

**Comment by joshrosso** [comment] 2017-02-26 19:02
I wonder if a band-aide solution could be a `--recover` flag which assumes the state of all control plane components in etcd in wrong, and proceeds to remedy the issue.

**Comment by aaronlevy** [comment] 2017-02-27 19:19
@joshrosso I'm a little unclear on the exact situation that needs resolving, and/or how one gets into this specific failure scenario. If you've lost the full control-plane, would we not consider this a scenario for "restore from etcd backup"?

Or is this specifically "we have etcd data, but all control plane nodes no longer exist & never will again?" -- this is a pretty drastic scenario, and a little unclear how you get here without really trying. Maybe by forcibly deleting all master nodes at the same time? Something we still need to cover - but I wonder if "restore from backup" is a sufficient near-term answer to this scenario.

Also, bootkube, in its current form, is expected to be used to bootstrap the first node - and then never used again (not even for disaster recovery). So using it in this way (on an existing cluster) is more or less out of scope for its current functionality.

Easily resolving disaster scenarios is obviously something we need to cover - so if you have reproduction steps for how a user might end up in this situation, we can start adding a matrix of scenarios we need to cover (e.g. restore from etcd backup, restore full/partial control-plane failure, etc.) - and how we plan to resolve those (bootkube, or separate tool, or documentation, etc.)

**Comment by aaronlevy** [comment] 2017-02-27 19:39
Actually, maybe "restore from etcd backup" and "restore from target etcd" are the two scenarios here that we need to resolve? I could see the latter being helpful, maybe in cases where we aren't self-hosting etcd?

**Comment by joshrosso** [comment] 2017-02-27 20:20
> Actually, maybe "restore from etcd backup" and "restore from target etcd" are the two scenarios here that we need to resolve?

Yes, exactly. I agree, it's a hard situation to get yourself in, but control plane recovery when all 'master' nodes are lost and new master node(s) must be spun up seems reasonable.

> Also, bootkube, in its current form, is expected to be used to bootstrap the first node - and then never used again (not even for disaster recovery).

Make sense. This makes this issue more of a design / feature request then. At least to me, it would make sense that in the case of full control plan loss (where new nodes are needed and checkpointing can't help you, bootkube could take on the responsibility of once again providing a 'temporary control plane' in order to recover. 

A key challenge is, the etcd data bootkube is restoring from could still state the control plane components are healthy. Thus needing some kind of feature, assuming this is an appropriate concern for bootkube to take on, where, through the temp api server, bootkube removes all kube-* deployments / daemonsets from etcd and attempt to redeploy on the newly available controller nodes.

What are your thoughts @aaronlevy? Is this a reasonable thing for bootkube to take on?

**Comment by aaronlevy** [comment] 2017-02-27 21:18
For bootkube to operate as a recovery tool - there are some behavior changes we would need to take into account. For example, the "temporary" control plane needs to source all data from etcd (component flags / tls assets / etc) - not necessarily pre-generated files (the temp control plane needs to exactly mimic the last known state of the cluster - last rendered state is likely stale/wrong).

This has been briefly discussed before (in regards to recovering from etcd backup):

```
1) ./bootkube recover --etcd-data-dir=foo (or --existing-etcd?)
2) starts temp etcd as static pod (skip if existing etcd)
3) extracts information about api-server directly from etcd (including necessary secret data) and starts temp api as static pod (with hostMounts for secret assets).
4) extracts podspec of scheduler and controller-manager from api-server, then creates pods using those specs pre-scheduled to local node (see https://github.com/kubernetes-incubator/bootkube/issues/112#issuecomment-250337461 for example process).
5) the temp scheduler and controller-manager pods will schedule replacements for themselves (and api-server), then we can kill them
6) We now have a functioning control plane.
```

**Comment by joshrosso** [comment] 2017-02-27 21:48
`--existing-etcd`, covering steps 3-6, would be a good starting point. It should be enough for people to get out of trouble in most cases.

`--etcd-data-dir` would make a nice addition too.

**Comment by joshrosso** [comment] 2017-02-28 02:42
@aaronlevy, are you open to PRs on this functionality? Or do you think we need more design discussion?

**Comment by aaronlevy** [comment] 2017-02-28 02:52
I would be open. I know @xiang90 was thinking about this tooling from a "recover self-hosted etcd from backup" perspective - where steps 1-3 would start a new "seed" etcd - then use etcd-operator to pivot into a working cluster.

But if we wanted to recover from existing / running etcd as well, could likely be developed side by side (`--existing-etcd` or some flag, VS `--etcd-data-dir`).

Thoughts @xiang90 ?

My requests might be that:
- Design doc PR would be helpful - just to make sure everyone is on the same page. (We may need to start a /Proposals top level directory).
- the code initially live in its own sub-command so we don't intermix the two modes (bootstrap vs recovery) in case we want to break these tools apart later (for example, bootkube vendors very specific versions of kubernetes - where a recover tool needs to be less opinionated and might be better served using client-go).

**Comment by hongchaodeng** [comment] 2017-02-28 03:56
> But if we wanted to recover from existing / running etcd as well

This could be achieved same as "recover from backup". It adds another step to "backup first".

**Comment by joshrosso** [comment] 2017-02-28 16:43
> Design doc PR would be helpful - just to make sure everyone is on the same page. (We may need to start a /Proposals top level directory).

I'll take this on. Let me know if you change your mind on it living in a top level `/proposals` directory.

> the code initially live in its own sub-command so we don't intermix the two modes 

ack

**Comment by xiang90** [comment] 2017-02-28 18:43
@joshrosso If we move to a fully self hosted world, I would expect most cases human operator needs to do `--with-etcd-dir` when the entire control panel fails since etcd will be part of it.

**Comment by joshrosso** [comment] 2017-02-28 22:35
@xiang90 Fair point. It would make sense then to prioritize the design and implementation of `--etcd-data-dir` (or `--with-etcd-dir`) over `--existing-etcd` described above.

**Comment by radhikapc** [comment] 2017-07-27 17:45
related to https://github.com/kubernetes-incubator/bootkube/issues/658

**Comment by aaronlevy** [comment] 2018-08-16 23:05
Closing, as a recovery subcommand was implemented

**Closed by aaronlevy** 2018-08-16 23:05 UTC
Labels: kind/design, needs/more-information
