### ISSUE TITLE
Node kubelet restart loop hogs CPU when using self-host-kubelet 

### ISSUE THREAD

**Issue by dhawal55** [kubernetes-incubator/bootkube#285] opened 2017-01-20 07:15 UTC
The example under `hack/multi-node/user-data.sample` uses the below systemd unit for node kubelet:
```
        [Service]
        EnvironmentFile=/etc/environment
        Environment=KUBELET_ACI=quay.io/coreos/hyperkube
        Environment=KUBELET_VERSION=v1.5.1_coreos.0
        Environment="RKT_OPTS=--volume var-lib-cni,kind=host,source=/var/lib/cni --mount volume=var-lib-cni,target=/var/lib/cni"
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/cni/net.d
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/checkpoint-secrets
        ExecStartPre=/bin/mkdir -p /srv/kubernetes/manifests
        ExecStartPre=/bin/mkdir -p /var/lib/cni
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --kubeconfig=/etc/kubernetes/kubeconfig \
          --require-kubeconfig \
          --cni-conf-dir=/etc/kubernetes/cni/net.d \
          --network-plugin=cni \
          --lock-file=/var/run/lock/kubelet.lock \
          --exit-on-lock-contention \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --allow-privileged \
          --hostname-override=${COREOS_PUBLIC_IPV4} \
          --node-labels=master=true \
          --cluster_dns=10.3.0.10 \
          --cluster_domain=cluster.local
        Restart=always
        RestartSec=5
```

However, if you use self-host-kubelet, the `--exit-on-lock-contention` causes the node kubelet to die and the `Restart=always` causes it to restart. This restart loop eats up all of my CPU on a m4.large AWS EC2 instance. Setting "Restart=on-failure" should work and documentation should be updated to highlight this.

**Comment by aaronlevy** [comment] 2017-01-20 21:25
I'm going to close this as a duplicate of https://github.com/kubernetes-incubator/bootkube/issues/251

If that's not the same behavior, let me know. Unfortunately the self-hosted kubelet hasn't been undergoing much testing / maintenance recently and there are some lingering issues. I also think we need to be more explicit about its current state: https://github.com/kubernetes-incubator/bootkube/issues/275

**Closed by aaronlevy** 2017-01-20 21:25 UTC
Labels: reviewed/duplicate
