### ISSUE TITLE
Build guidelines to avoid missing P224

### ISSUE THREAD

**Issue by dghubble** [kubernetes-incubator/bootkube#150] opened 2016-10-12 08:18 UTC
Kubernetes build issues such as https://github.com/kubernetes/kubernetes/issues/29534 propagate into bootkube since kubernetes is a vendored component. RHEL/Fedora don't include P224 for some license reasons and builds in this environment fail

```
Name        : golang
Version     : 1.6.3
Release     : 2.fc24
Architecture: x86_64
```

```
make install
mkdir -p _output/bin/linux/
GOOS=linux go build -ldflags "-X github.com/kubernetes-incubator/bootkube/pkg/version.Version=v0.2.0" -o _output/bin/linux/bootkube github.com/kubernetes-incubator/bootkube/cmd/bootkube
# github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/util/certificates
vendor/k8s.io/kubernetes/pkg/util/certificates/csr.go:96: undefined: elliptic.P224
# github.com/kubernetes-incubator/bootkube/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/x509.go:342: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:355: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:1461: undefined: elliptic.P224
Makefile:27: recipe for target '_output/bin/linux/bootkube' failed
make: *** [_output/bin/linux/bootkube] Error 2
```

Using the binary from the go1.7.1 linux/amd64 tarball does seem to allow builds to succeed as reported upstream. It doesn't appear much could be done within bootkube to address this except re-vendoring when upstream reaches a conclusion.

Perhaps I'll add a Go version note to the README for now?

cc @gtank

**Comment by aaronlevy** [comment] 2016-10-12 17:20
Also not exactly a solution, but we could have the `make release` target use the containerized build to mitigate this (https://github.com/kubernetes-incubator/bootkube/blob/master/build/build-release.sh) -- but that also assumes host has rkt installed.

**Comment by gtank** [comment] 2016-10-12 18:34
Using the binary Go releases will always solve this problem. The problem is Fedora packagers [explicitly removing](https://bugzilla.redhat.com/show_bug.cgi?id=1038683) ECC support from the Go that ships in their repos. They do the same for [openssl](https://bugzilla.redhat.com/show_bug.cgi?id=319901) - my understanding is it's something to do with patent risk (cc @mjg59?)

**Comment by dghubble** [comment] 2016-10-12 18:55
@aaronlevy yes! rkt-based builds would be nice

**Comment by aaronlevy** [comment] 2016-12-30 20:13
Gonna close this, but let me know if it should be re-opened

**Closed by aaronlevy** 2016-12-30 20:13 UTC
