### ISSUE TITLE
Multiple automated master nodes (e.g. in autoscaling group)

### ISSUE THREAD

**Issue by lewismarshall** [kubernetes-incubator/bootkube#342] opened 2017-03-01 17:41 UTC
See issue https://github.com/kubernetes/kubeadm/issues/184 - same issue as kubeadm.

I would like to be able to use bootkube to bootstrap a cluster (if it didn't exist) and to join a cluster if it does.

I'm having trouble working out how to use bootkube in an automated fashion if the master resources are all created on a single node only.

Can anyone help as the direction seems to pertain to a manual only tool for single master nodes.

**Comment by aaronlevy** [comment] 2017-03-01 19:36
Similar discussion about documenting multi-master setups: https://github.com/kubernetes-incubator/bootkube/issues/311

Bootkube itself should only be used once on the very first node. It is not used to "join" nodes -- all that should require is running kubelet with a kubeconfig which can securely contact an api-server.

The general process would be to have two auto-scaling groups, one for masters and one for workers. The only difference in their user-data would likely be the `--node-labels=master=true` on the kubelet (so the node registers itself as a master). Note that this label will change soon: https://github.com/kubernetes-incubator/bootkube/issues/246

Then you can scale deployments to spread them across these master nodes (`kubectl scale deployment kube-scheduler --namespace=kube-system --replicas=X`). These components will automatically be spread across nodes soon as well: https://github.com/kubernetes-incubator/bootkube/issues/166

I'm going to close this as a duplicate of https://github.com/kubernetes-incubator/bootkube/issues/311, however - as we do need to better document this process - and should try and keep discussion centralized. But there isn't really much restricting you to a single master at this point - it's just a matter of adding more nodes and making sure your "master" nodes are behind a load-balancer or DNS.

**Closed by aaronlevy** 2017-03-01 19:36 UTC
