### ISSUE TITLE
Self-hosted kubelet not working correctly

### ISSUE THREAD

**Issue by bassam** [kubernetes-incubator/bootkube#251] opened 2016-12-29 20:18 UTC
I added the `--self-host-kubelet=true` flag to `hack/multi-node/bootkube-up` and launched a cluster.

The kubelet pivot seems to succeed but then on-host kubelet keep restarting and failing binding a socket, and not exiting gracefully when seeing the lock is acquired by the self-hosted kubelet:

```Dec 28 18:24:00 w1 systemd[1]: Starting kubelet.service...
Dec 28 18:24:00 w1 systemd[1]: Started kubelet.service.
Dec 28 18:24:00 w1 kubelet-wrapper[11841]: image: using image from file /usr/lib64/rkt/stage1-images/stage1-fly.aci
Dec 28 18:24:00 w1 kubelet-wrapper[11841]: image: using image from local store for image name quay.io/coreos/hyperkube:v1.5.1_coreos.0
Dec 28 18:24:15 w1 kubelet-wrapper[11841]: I1228 18:24:15.896894   11841 server.go:312] acquiring file lock on "/var/run/lock/kubelet.lock"
Dec 28 18:24:15 w1 kubelet-wrapper[11841]: I1228 18:24:15.897636   11841 server.go:317] watching for inotify events for: /var/run/lock/kubelet.lock
Dec 28 18:24:15 w1 kubelet-wrapper[11841]: I1228 18:24:15.900488   11841 feature_gate.go:181] feature gates: map[]
Dec 28 18:24:15 w1 kubelet-wrapper[11841]: I1228 18:24:15.932580   11841 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:15.933192   11841 docker.go:376] Start docker client with request timeout=2m0s
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.363777   11841 manager.go:143] cAdvisor running in container: "/system.slice/kubelet.service"
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: W1228 18:24:16.396474   11841 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.430887   11841 fs.go:117] Filesystem partitions: map[/dev/sda9:{mountpoint:/var/lib/docker major:8 minor:9 fsType:ext4 blockSize:0} /dev/sda3:{mountpoint:/etc/ssl/certs major:8 minor:3 fsType:ext4 blockSize:0}]
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.432930   11841 manager.go:198] Machine: {NumCores:1 CpuFrequency:2730824 MemoryCapacity:1045471232 MachineID:cf742c5b2ef64b18a93d3785f5444d22 SystemUUID:7DA693DA-2CC1-4EEE-8BA1-0157BB55C2B1 BootID:2d6d518a-dbe8-469d-b2c2-99fc27eaa68a Files
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.433546   11841 manager.go:204] Version: {KernelVersion:4.7.3-coreos-r3 ContainerOsVersion:CoreOS 1185.5.0 (MoreOS) DockerVersion:1.11.2 CadvisorVersion: CadvisorRevision:}
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.446561   11841 cadvisor_linux.go:152] Failed to register cAdvisor on port 4194, retrying. Error: listen tcp :4194: bind: address already in use
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.461171   11841 kubelet.go:242] Adding manifest file: /etc/kubernetes/manifests
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.462070   11841 kubelet.go:252] Watching apiserver
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: W1228 18:24:16.466568   11841 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.466590   11841 kubelet.go:477] Hairpin mode set to "hairpin-veth"
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.596900   11841 docker_manager.go:257] Setting dockerRoot to /var/lib/docker
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.599154   11841 docker_manager.go:260] Setting cgroupDriver to cgroupfs
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.661426   11841 server.go:770] Started kubelet v1.5.1+coreos.0
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: E1228 18:24:16.661855   11841 server.go:481] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: E1228 18:24:16.690722   11841 kubelet.go:1145] Image garbage collection failed: unable to find data for container /
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.692639   11841 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: I1228 18:24:16.695395   11841 server.go:123] Starting to listen on 0.0.0.0:10250
Dec 28 18:24:16 w1 kubelet-wrapper[11841]: F1228 18:24:16.713335   11841 server.go:132] listen tcp 0.0.0.0:10250: bind: address already in use
Dec 28 18:24:16 w1 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 28 18:24:16 w1 systemd[1]: kubelet.service: Unit entered failed state.
Dec 28 18:24:16 w1 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 28 18:24:21 w1 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Dec 28 18:24:21 w1 systemd[1]: Stopped kubelet.service.
Dec 28 18:24:21 w1 systemd[1]: Starting kubelet.service...
Dec 28 18:24:21 w1 systemd[1]: Started kubelet.service.
```
Its possible that this is due to /var/run not being bind mounted correctly as noted by @aaronlevy

**Comment by aaronlevy** [comment] 2016-12-29 23:19
Manually tested this and saw the same thing. Did a quick test adding mount for /var/run to $RKT_OPTS in the kubelet.service unit -- but didn't resolve the issue.

Not going to be able to take a deeper look at this immediately, but just wanted to note that I'm seeing the same behavior.

**Comment by bassam** [comment] 2016-12-29 23:22
@aaronlevy can you help me understand why we `nsenter --target=1 --mount --wd=.` is needed when launching the self-hosted kubelet. Could this be interfering?

**Comment by aaronlevy** [comment] 2016-12-29 23:33
My initial thought is that it shouldn't be interfering. Basically it just means the self-hosted kubelet will be in the host mount namespace - and for the kubelet process specifically - it will see the container FS as its root filesystem.

It is needed so that mount tools operate in the hosts mount namespace. Otherwise mounts like secrets/configmaps/volumes would be within the kubelet container's filesystem/namespace and if it was restarted, they would be recreated in the next kubelet container (whereas the pods themselves would still be running referencing the old mounts).

However, I was planning on dropping that workaround soon, and using the `--containerized` flag -- which tells the kubelet that it should use a special path `/rootfs` when creating mounts.

See:
https://github.com/kubernetes-incubator/bootkube/pull/247#discussion_r94185933
https://github.com/kubernetes-incubator/bootkube/pull/162

Also, just to confirm, it does look like we're still properly mounting /run in both on-host and self-hosted kubelet:

https://github.com/coreos/coreos-overlay/blob/master/app-admin/kubelet-wrapper/files/kubelet-wrapper#L71

https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L64-L65

And this definitely worked at some point - so we introduced a regression at some point (I've been a little more lax on testing self-hosted kubelet since defaulting it to off ...)

**Comment by pbx0** [comment] 2017-01-04 18:55
I'm not sure what exactly is going on yet, but, just going to post some of my testing updates here. I can reproduce this issue with:
k8s: 1.4.7, 1.5.1  
CoreOS: 1235.0.0 
bootkube at master branch

The host kubelet first exits not because it detects lock contention but because:
`systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.`

After that restart the self-hosted kubelet grabs the listening address and the host kubelet crashloops. 

Something odd is going on with the lock coordination.
```
$ lsof /var/lock/kubelet.lock
Output information may be incomplete.
lsof: WARNING: can't stat() cgroup file system /var/lib/rkt/pods/run/cc9711a2-d30c-42f5-9f19-14f4e3b8c3dc/stage1/rootfs/opt/stage2/hyperkube/rootfs/sys/fs/cgroup/pids
      Output information may be incomplete.
lsof: WARNING: can't stat() pstore file system /var/lib/rkt/pods/run/cc9711a2-d30c-42f5-9f19-14f4e3b8c3dc/stage1/rootfs/opt/stage2/hyperkube/rootfs/sys/fs/pstore
      Output information may be incomplete.
lsof: WARNING: can't stat() selinuxfs file system /var/lib/rkt/pods/run/cc9711a2-d30c-42f5-9f19-14f4e3b8c3dc/stage1/rootfs/opt/stage2/hyperkube/rootfs/sys/fs/selinux
<SNIP ... this goes on awhile>
```

```
$ flock -x /var/lock/kubelet.lock
flock: bad file descriptor: '/var/lock/kubelet.lock'
```

**Comment by aaronlevy** [comment] 2017-01-09 22:56
fwiw, I think the "bad file descriptor" message is because no command was provided:

`sudo flock -x /var/lock/kubelet.lock echo foo` should work

**Comment by dghubble** [comment] 2017-10-27 21:53
`--self-hosted-kubelet` is marked deprecated and will be removed in a future release.

**Closed by dghubble** 2017-10-27 21:53 UTC
Labels: kind/bug, priority/P3
