### ISSUE TITLE
Flannel Daemon Set does not have a health check in templates.go

### ISSUE THREAD

**Issue by rithujohn191** [kubernetes-incubator/bootkube#402] opened 2017-03-24 17:17 UTC
bootkube/pkg/asset/internal/templates.go does not have health check for KubeFlannelTemplate. Is this intentional? We noticed a case where flannel failed to connect to the API server the first time around but manually bringing it up again seemed to have worked.

@aaronlevy @ericchiang

**Comment by aaronlevy** [comment] 2017-03-24 17:43
Not immediately sure what we could health-check from flannel. It is okay that flannel can lose access to the api-server, it should just keep re-trying (so we likely would not want a health-check based on api-server connectivity that triggers destruction of the pod). Transient network failures should be expected / okay.

Are there any more details on the issue (flannel logs or reproduction steps?). What were your steps to manually bring it up? If it was never able to connect to the api, that's a bug we should look into.

**Comment by ericchiang** [comment] 2017-03-24 18:33
@aaronlevy this was an issue with the pod CIDR conflicting with the docker bridge. For some reason, when we showed up to the cluster, flannel wasn't able to connect to the API server (it was just spinning in a loop). That turned out to be unrelated, and we "restarted" flannel just by deleting the pods and having flannel come back up.

It's more of a bad debugging experience then a bug, because kubernetes reports it as healthy. But I can also see that it might be dangerous to consistently be restarting flannel. I don't think I have a strong opinion about this.

**Comment by aaronlevy** [comment] 2017-03-24 18:59
Any more details on podcidr/docker bridge conflict? The docker default is 172.18.0.1/16 and our default is 10.2.0.0/16 -- was this a case where the podcidr was changed to a range that conflicts with docker? Might be something we need to account for if that's the case.

**Comment by aaronlevy** [comment] 2017-03-24 19:01
Also just to note, it is preferable that flannel continues to run normally with whatever state it does have even if api-server is unavailable - so a healthcheck on api-server connectivity is likely a non-starter.

**Comment by ericchiang** [comment] 2017-03-24 20:11
> Any more details on podcidr/docker bridge conflict? The docker default is 172.18.0.1/16 and our default is 10.2.0.0/16 -- was this a case where the podcidr was changed to a range that conflicts with docker?

Someone tried to customize it.

> so a healthcheck on api-server connectivity is likely a non-starter.

Agreed. Maybe we'll close this issue for now until we can define a better requirement for health checking?

**Closed** 2019-06-20 04:56 UTC
Labels: kind/question, lifecycle/rotten, needs/more-information, triage/support
