### ISSUE TITLE
make single-node hangs

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-incubator/bootkube#362] opened 2017-03-09 18:26 UTC
After PR #345 was merged, I am no longer able to run `make run-single` successfully. It always hangs at the same step, and eventually times out.

```
Creating self-hosted assets...
	created          kube-apiserver secret
	created          kube-apiserver daemonset
	created kube-controller-manager poddisruptionbudget
	created kube-controller-manager secret
	created kube-controller-manager deployment
	created                kube-dns deployment
	created                kube-dns service
	created        kube-flannel-cfg configmap
	created            kube-flannel daemonset
	created              kube-proxy daemonset
	created          kube-scheduler poddisruptionbudget
	created          kube-scheduler deployment
	created       system:default-sa clusterrolebinding
	created    checkpoint-installer daemonset
	Pod Status:        pod-checkpointer	DoesNotExist
	Pod Status:          kube-apiserver	DoesNotExist
	Pod Status:          kube-scheduler	Pending
	Pod Status: kube-controller-manager	Pending
Error: error while checking pod status: timed out waiting for the condition
```

Is there additional configuration required to run the hack scripts now?

**Comment by aaronlevy** [comment] 2017-03-09 18:39
There shouldn't be any new configuration required, so this could be a regression. Our PR tests have been in a pretty flaky state recently - so this got merged with some issues that weren't surfaced (e.g. https://github.com/kubernetes-incubator/bootkube/pull/360)

/cc @ericchiang

**Comment by ericchiang** [comment] 2017-03-09 18:58
It looks like `hack/single-node/bootkube-up` doesn't copy the CA file over. Working on a fix.

**Comment by carolynvs** [comment] 2017-03-09 22:54
I just pulled latest (ca299d1b242260efe4c40d0b985e7b8f5068efba) and `make run-single` is still failing, though `make run-multi` is working fine now.

```
$ make run-single
...
==> default: Machine booted and ready!
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mv:
==> default: cannot move '/tmp/kubeconfig' to '/etc/kubernetes/kubeconfig'
==> default: : No such file or directory
```

Using `vagrant ssh` I logged into the node and see that `/tmp/kubeconfig` exists. Also `sudo mv /tmp/kubeconfig /etc/kubernetes/kubeconfig` works fine. 

I'm not sure if there is still a problem with the single-node hack script or if this is a problem on my end?

**Comment by aaronlevy** [comment] 2017-03-09 23:43
@carolynvs I'm seeing the same thing - after I tested, I made one more change to the PR, but didn't re test - the change that I made was removing the (now) unused write-files directive in the user-data (https://github.com/kubernetes-incubator/bootkube/pull/363/files#diff-79c78182dd06186c28ad19cc7a616083L53).

Likely need to add a `mkdir /etc/kubernetes`. The dir exists once you SSH in because the kubelet service will also try and create it. 

Sorry about that. I assumed it was a no-op change - should have re-tested.

**Comment by aaronlevy** [comment] 2017-03-09 23:52
Try this one more time: https://github.com/kubernetes-incubator/bootkube/pull/364

**Comment by aaronlevy** [comment] 2017-03-10 19:06
Gonna close this again - let me know if you have any issues.

**Closed by aaronlevy** 2017-03-10 19:06 UTC
Labels: kind/bug, priority/P0

**Comment by carolynvs** [comment] 2017-03-10 19:09
Thanks, it's working again! 👍
