### ISSUE TITLE
Documentation: using alternative CNI plugins

### ISSUE THREAD

**Issue by aaronlevy** [kubernetes-incubator/bootkube#407] opened 2017-03-29 14:28 UTC
Calico / Canal etc. They're all deployed as CNI plugins so they hopefully should be fairly interchangeable. As this is tested - we should add the process to the documentation.

**Comment by bzub** [comment] 2017-03-29 14:48
I'll try to help out since I often deploy new clusters with bootkube and calico.

I haven't tried replacing flannel with calico on a running cluster, but there's already documentation on that elsewhere.

**Comment by alanmeadows** [comment] 2017-04-06 01:51
We're trying to leverage calico (and avoid flannel coming into the picture altogether) during the bootstrap process, as calico is the target state.  We're running into issues.

@bzub Do you by any chance have steps that work that you could share for initializing using calico vs flannel prior to full blown documentation?

**Comment by bzub** [comment] 2017-04-06 02:51
@alanmeadows  Yes I'll share my manifests soon. Essentially I used the stock Calico yaml files and edited based on their documentation, and replaced the two flannel manifests that `bootkube render` generates with calico. The filenames just have​ to match the old flannel names so `bootkube start` uses them. It was surprisingly simple.

**Comment by bzub** [comment] 2017-04-06 03:17
Here's the [manifests and the filenames](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f
) I used directly with bootkube.
They are based on [these manifests from Calico](http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/calico.yaml).

I believe the only modifications I made were to:
- Separate the [configmap](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f#file-kube-flannel-cfg-yaml) from the [rest of the resources](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f#file-kube-flannel-yaml) as bootkube expects
- [Change the etcd endpoint](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f#file-kube-flannel-cfg-yaml-L9) in the configmap to what works with my DNS setup
- Comment out the [volumes](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f#file-kube-flannel-yaml-L129) and [volumeMounts](https://gist.github.com/bzub/64c2b3a695cff73b89df409077911c7f#file-kube-flannel-yaml-L105) pertaining to etcd TLS secrets since I don't use them 

Please note I haven't tried this with self-hosted etcd nor kubelet.

**Comment by aric49** [comment] 2017-04-07 14:54
Hello @bzub -- Thank you for your quick reply and manifests for using Calico.   I know you stated that you had not tested your Calico using the self-hosted etcd, but currently I am seeing a slight issue deploying this with the self hosted model.   Please note, we are using a non-self hosted kubelet, but a self hosted etcd.

I have pulled your manifests directly and the only modification I am making is supplying our self-hosted etcd IP in the `kube-flannel-cfg.yaml` file.  When I put in the IP address of the kube-etcd service (10.3.0.15), I am seeing all of our containers hang at `ContainerCreating` once the kubelet starts. During this time, our calico pods are in `CrashLoop` or `Error` state.  We are also seeing this behavior if I supply the localhost IP address: `127.0.0.1:2379`.    The only way I can see the pods create correctly and go into running state is if I supply the bootkube temporary ETCD server IP:    `127.0.0.1:12379`, but once bootkube stops itself and pivots over to the self-hosted etcd, the calico pods go down since the etcd is no longer listening on port 12379.

In summary, I am seeing the following issues when I supply various etcd server IPs for the `etcd_endpoints:` parameter:

1) kube-etcd service endpoint:  10.3.0.15 ->  pods that require calico networking hang at `ContainerCreating`,  Calico is in `CrashLoop` or `Error state`,  since calico cannot reach the self-hosted ETCD yet. 

2) Localhost IP at port 2379(127.0.0.1:2379) -> pods that require calico networking hang at `ContainerCreating`,  Calico is in `CrashLoop` or `Error state`, since Calico cannot reach the self-hosted ETCD yet. 

3) Bootkube Temporary ETCD server (127.0.0.1:12379):   Pods spin up correctly, and go into `running` state but calico fails once the temporary `etcd` server goes away.

A solution I can see is for Calico to leverage its own etcd server, which I believe previous versions of calico did exactly that (Doesn't appear that this functionality is in your manifests), or have calico somehow fail over from the temporary bootkube etcd server to the cluster etcd server once bootkube goes away.  

Let me know if you have any thoughts or potential solutions for this @bzub or require any further information.  For reference my bootkube/kubelet version details are below:

Bootkube:   v0.3.12
Kubelet:  v1.5.6 
CNI:   v0.5.1

**Comment by bzub** [comment] 2017-04-11 02:55
Hi @aric49. Thanks for the details of your issue.  The big difference between Flannel and Calico in terms of Bootkube is that Flannel is passed the `--kube-subnet-mgr` option which I believe results in Flannel not using etcd and instead uses the Kubernetes API server as an abstraction in front of etcd.  So if you don't mind the limitations, you could try Calico's similar [Etcdless Hosted Install](http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/k8s-backend/).

The Calico using its own etcd server/cluster option is basically what I use.  It's just a matter of configuration that my Bootkube installation uses the same etcd cluster as Calico.  So you could always go that route for Calico, and still use self-hosted etcd for Kubernetes.  If you would still like to attempt using self-hosted etcd for Calico, the next release of Bootkube could have the answer.  #418 was recently merged which appears to provide kube-apiserver with etcd endpoints for both the temporary plane and final Kubernetes cluster.  If I'm not mistaken these same endpoints could potentially be used in the Calico configuration manifest so it fails over, in a sense.

When you use the temporary etcd server (127.0.0.1:12379) as the endpoint does the Kubernetes cluster at least spin up the kube-apiserver(s) pods?  I would think they would start up because they use `hostNetworking`.  In that case, you could probably modify calico configmap with the new self-hosted etcd endpoint(s) on the final Kubernetes cluster.

**Comment by aric49** [comment] 2017-04-20 13:56
Hey @bzub -- sorry for the delay in responding. I was doing some experimenting with the deployment using calico to replace the default flannel manifests and we were able to get our deployment at least semi-functional using the etcdless calico manifest. Unfortunately though, we need the full etcd capabilities of calico for our specific use cases, so this is more of a stop-gap solution.   We also did some experimentation with replacing the etcdless calico with the full hosted etcd calico manifest once we were able to get the cluster up and running.   However, we seem to be running into weird bugs when we do this.  For example, we are observing that sometimes different pods such as the api-server, or kube-dns goes into crashloop and never recovers.   Other issues we are seeing is that we cannot schedule workloads once the full cluster has come up.

It is possible that this instability could be caused by calico in conjunction bootkube, but it is quite difficult to nail down the root cause as of yet. I am also having some difficulty understanding what exactly is currently supported by bootkube in terms of switching out the default flannel CNI. It seems odd to me that the method would be to replace the flannel yamls with yaml files for other providers. Are there any plans to make this process more transparent in the way of documentation, or parameters we can pass into bootkube when we render it?  I think ideally, the operator should have an option to chose a CNI provider with a flag similar to:    `bootkube render --cni-provider=calico`, and provide a default manifest for a selfhosted calico/canal/flannel/romana/etc.   In the interim, perhaps provide documentation describing how to do this. Any thoughts?

**Comment by aaronlevy** [comment] 2017-04-28 23:48
Unfortunately I'm not super familiar with other CNI plugins - so I can't be of immediate help. However, it should ideally just be replacing the flannel manifests with whatever CNI plugin you wish to use (although I've never personally tested this).

From an architectural perspective, I would prefer that the only access to the cluster-etcd is from the api-server (access to etcd is essentially root on the cluster). But short of firewall rules, there's nothing immediately enforcing this in bootkube - so it's still an administrator's choice.

I wouldn't be opposed to allowing the render step to use a different CNI plugin -- but each supported plugin would likely would need to be something community supported (as I'm not personally knowledgeable of the different tools).

**Comment by bzub** [comment] 2017-05-26 18:30
I've written [documentation and manifests](https://github.com/cloudnativelabs/kube-router/tree/master/contrib/bootkube) to use [kube-router](https://github.com/cloudnativelabs/kube-router) with Bootkube as an alternative to both kube-proxy and flannel.  It also provides NetworkPolicy enforcement.  I'd be willing to submit a PR that adds a link to the documentation if there's any interest.

**Comment by SEJeff** [comment] 2017-05-31 20:21
@bzub there is definitely interest, thanks!

**Comment by v1k0d3n** [comment] 2017-06-03 13:46
@bzub this is definitely interesting. i started working on a [bootkube-ci](https://github.com/v1k0d3n/bootkube-ci) repo, just so i can quickly standup and tear down bootkube deployments, and I have simply been auto-removing the flannel manifests and deploying custom calico/canal manifests (with policy enforcement). i will have to check out your suggestion for kube-router...it's definitely interesting and something we need to explore (i'm on the same team as @aric49 and @alanmeadows).

**Closed** 2017-10-02 19:00 UTC
Labels: help wanted, kind/documentation, priority/P2
