### ISSUE TITLE
bootkube support for GCE as cloud provider

### ISSUE THREAD

**Issue by rimusz** [kubernetes-incubator/bootkube#571] opened 2017-06-07 17:05 UTC
enabling GCE as cloud provider gives such error:
```
kubelet_node_status.go:73] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: googleapi: Error 403: Insufficient Permission, insufficientPermissions
```
So PVCs, no LBs can be created.
Instances have full API access.

**Comment by rimusz** [comment] 2017-06-07 17:08
adding scopes as below did not help:
```
gcloud compute instances create ${CLUSTER_PREFIX}-core1 \
  --image-project coreos-cloud --image-family coreos-stable \
  --zone ${ZONE} --machine-type n1-standard-1 --scopes cloud-platform,storage-rw,compute-rw,logging-write,monitoring,monitoring-write,service-control,service-management,sql,sql-admin,storage-full,taskqueue
```

**Comment by dghubble** [comment] 2017-06-07 17:16
You may want to read through https://github.com/kubernetes-incubator/bootkube/issues/463

**Comment by rimusz** [comment] 2017-06-07 17:39
oh, upstream bug, not really easy to solve then :(

**Comment by aaronlevy** [comment] 2017-06-22 16:40
I'm going to close this as a duplicate of https://github.com/kubernetes-incubator/bootkube/issues/463 so we can keep discussion in one place.

**Closed by aaronlevy** 2017-06-22 16:40 UTC
Labels: kind/bug, priority/P1
